version: "3.9"
services:
  api:
    build: ./apps/api
    ports:
      - "8000:8000"
    env_file:
      - ./apps/api/.env.example
  web:
    build: ./apps/web
    ports:
      - "8080:8080"
    env_file:
      - ./apps/web/.env.example
    depends_on:
      - api
