services:
  mongo:
    image: mongo:7
    ports: ["27017:27017"]
    volumes: [mongodata:/data/db]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: ./apps/api
      target: prod
    env_file: ./apps/api/.env.example
    environment:
      - MONGO_URL=${MONGO_URL:-mongodb://mongo:27017/growverse}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:5173}
    ports: ["8000:8000"]
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy

  web:
    build:
      context: ./apps/web
      target: prod
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:8000}
    ports: ["8080:8080"]
    depends_on:
      - api

volumes:
  mongodata:
